//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 02:50:30 PM ICT 
//


package com.theerut.springj11.client.webservice.customersearch;

import com.theerut.springj11.client.webservice.common.EXAMSignonRqType;
import com.theerut.springj11.client.webservice.common.EXAMSignonRsType;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_SignonRq"/>
 *           &lt;element name="EXAM_CustSearchRq" type="{urn:ifxforum-org:XSD:1}EXAM_CustSearchRq_Type"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_SignonRs"/>
 *           &lt;element name="EXAM_CustSearchRs" type="{urn:ifxforum-org:XSD:1}EXAM_CustSearchRs_Type"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="coreSchemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "examSignonRq",
    "examCustSearchRq",
    "examSignonRs",
    "examCustSearchRs"
})
@XmlRootElement(name = "EXAM_CustSearchOpr")
public class EXAMCustSearchOpr {

    @XmlElement(name = "EXAM_SignonRq")
    protected EXAMSignonRqType examSignonRq;
    @XmlElement(name = "EXAM_CustSearchRq")
    protected EXAMCustSearchRqType examCustSearchRq;
    @XmlElement(name = "EXAM_SignonRs")
    protected EXAMSignonRsType examSignonRs;
    @XmlElement(name = "EXAM_CustSearchRs")
    protected EXAMCustSearchRsType examCustSearchRs;
    @XmlAttribute(name = "coreSchemaVersion", required = true)
    protected BigDecimal coreSchemaVersion;

    /**
     * Gets the value of the examSignonRq property.
     *
     * @return
     *     possible object is
     *     {@link EXAMSignonRqType }
     *
     */
    public EXAMSignonRqType getEXAMSignonRq() {
        return examSignonRq;
    }

    /**
     * Sets the value of the examSignonRq property.
     *
     * @param value
     *     allowed object is
     *     {@link EXAMSignonRqType }
     *
     */
    public void setEXAMSignonRq(EXAMSignonRqType value) {
        this.examSignonRq = value;
    }

    /**
     * Gets the value of the examCustSearchRq property.
     *
     * @return
     *     possible object is
     *     {@link EXAMCustSearchRqType }
     *
     */
    public EXAMCustSearchRqType getEXAMCustSearchRq() {
        return examCustSearchRq;
    }

    /**
     * Sets the value of the examCustSearchRq property.
     *
     * @param value
     *     allowed object is
     *     {@link EXAMCustSearchRqType }
     *
     */
    public void setEXAMCustSearchRq(EXAMCustSearchRqType value) {
        this.examCustSearchRq = value;
    }

    /**
     * Gets the value of the examSignonRs property.
     *
     * @return
     *     possible object is
     *     {@link EXAMSignonRsType }
     *
     */
    public EXAMSignonRsType getEXAMSignonRs() {
        return examSignonRs;
    }

    /**
     * Sets the value of the examSignonRs property.
     *
     * @param value
     *     allowed object is
     *     {@link EXAMSignonRsType }
     *
     */
    public void setEXAMSignonRs(EXAMSignonRsType value) {
        this.examSignonRs = value;
    }

    /**
     * Gets the value of the examCustSearchRs property.
     *
     * @return
     *     possible object is
     *     {@link EXAMCustSearchRsType }
     *
     */
    public EXAMCustSearchRsType getEXAMCustSearchRs() {
        return examCustSearchRs;
    }

    /**
     * Sets the value of the examCustSearchRs property.
     *
     * @param value
     *     allowed object is
     *     {@link EXAMCustSearchRsType }
     *     
     */
    public void setEXAMCustSearchRs(EXAMCustSearchRsType value) {
        this.examCustSearchRs = value;
    }

    /**
     * Gets the value of the coreSchemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoreSchemaVersion() {
        return coreSchemaVersion;
    }

    /**
     * Sets the value of the coreSchemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoreSchemaVersion(BigDecimal value) {
        this.coreSchemaVersion = value;
    }


}
