//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 02:50:30 PM ICT 
//


package com.theerut.springj11.client.webservice.customersearch;

import com.theerut.springj11.client.webservice.common.EXAMGovIssueIdentType;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EXAM_CustSearch_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EXAM_CustSearch_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}CustPermId" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_NameAliasInd" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_CustomerName" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}LegalName" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_Indicator" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_IdentSerialNum" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_GovIssueIdentType" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}Country" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_CustCategory" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}BirthDt" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_CountryofCitizenship" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_CustSegmentCode" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_InsiderCode" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}CustType" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_CustCreatedDt" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_OfficerCode" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_ShortName" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_PreAuthInd" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_EmployeeCode" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_ProviderSystemCode" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_SearchSelection" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_SearchOption" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_Filler" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_OfficerName" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_AltId" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_CustSubCategory" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_StrategicBusinessUnit" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_SubSBUCode" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}AcctId" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}AcctType" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_CloseAcctFlag" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_ConsolAcctId" minOccurs="0"/>
 *         &lt;element ref="{urn:ifxforum-org:XSD:1}EXAM_RelationshipCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EXAM_CustSearch_Type", propOrder = {
    "custPermId",
    "examNameAliasInd",
    "examCustomerName",
    "legalName",
    "examIndicator",
    "examIdentSerialNum",
    "examGovIssueIdentType",
    "country",
    "examCustCategory",
    "birthDt",
    "examCountryofCitizenship",
    "examCustSegmentCode",
    "examInsiderCode",
    "custType",
    "examCustCreatedDt",
    "examOfficerCode",
    "examShortName",
    "examPreAuthInd",
    "examEmployeeCode",
    "examProviderSystemCode",
    "examSearchSelection",
    "examSearchOption",
    "examFiller",
    "examOfficerName",
    "examAltId",
    "examCustSubCategory",
    "examStrategicBusinessUnit",
    "examSubSBUCode",
    "acctId",
    "acctType",
    "examCloseAcctFlag",
    "examConsolAcctId",
    "examRelationshipCode"
})
public class EXAMCustSearchType {

    @XmlElement(name = "CustPermId")
    protected String custPermId;
    @XmlElement(name = "EXAM_NameAliasInd")
    protected String examNameAliasInd;
    @XmlElement(name = "EXAM_CustomerName")
    protected String examCustomerName;
    @XmlElement(name = "LegalName")
    protected String legalName;
    @XmlElement(name = "EXAM_Indicator")
    protected String examIndicator;
    @XmlElement(name = "EXAM_IdentSerialNum")
    protected String examIdentSerialNum;
    @XmlElement(name = "EXAM_GovIssueIdentType")
    protected String examGovIssueIdentType;
    @XmlElement(name = "Country")
    protected String country;
    @XmlElement(name = "EXAM_CustCategory")
    protected String examCustCategory;
    @XmlElement(name = "BirthDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDt;
    @XmlElement(name = "EXAM_CountryofCitizenship")
    protected String examCountryofCitizenship;
    @XmlElement(name = "EXAM_CustSegmentCode")
    protected String examCustSegmentCode;
    @XmlElement(name = "EXAM_InsiderCode")
    protected String examInsiderCode;
    @XmlElement(name = "CustType")
    protected String custType;
    @XmlElement(name = "EXAM_CustCreatedDt")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar examCustCreatedDt;
    @XmlElement(name = "EXAM_OfficerCode")
    protected String examOfficerCode;
    @XmlElement(name = "EXAM_ShortName")
    protected String examShortName;
    @XmlElement(name = "EXAM_PreAuthInd")
    protected String examPreAuthInd;
    @XmlElement(name = "EXAM_EmployeeCode")
    protected String examEmployeeCode;
    @XmlElement(name = "EXAM_ProviderSystemCode")
    protected String examProviderSystemCode;
    @XmlElement(name = "EXAM_SearchSelection")
    protected String examSearchSelection;
    @XmlElement(name = "EXAM_SearchOption")
    protected String examSearchOption;
    @XmlElement(name = "EXAM_Filler")
    protected String examFiller;
    @XmlElement(name = "EXAM_OfficerName")
    protected String examOfficerName;
    @XmlElement(name = "EXAM_AltId")
    protected EXAMGovIssueIdentType examAltId;
    @XmlElement(name = "EXAM_CustSubCategory")
    protected String examCustSubCategory;
    @XmlElement(name = "EXAM_StrategicBusinessUnit")
    protected String examStrategicBusinessUnit;
    @XmlElement(name = "EXAM_SubSBUCode")
    protected String examSubSBUCode;
    @XmlElement(name = "AcctId")
    protected String acctId;
    @XmlElement(name = "AcctType")
    protected String acctType;
    @XmlElement(name = "EXAM_CloseAcctFlag")
    protected String examCloseAcctFlag;
    @XmlElement(name = "EXAM_ConsolAcctId")
    protected String examConsolAcctId;
    @XmlElement(name = "EXAM_RelationshipCode")
    protected String examRelationshipCode;

    /**
     * Gets the value of the custPermId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustPermId() {
        return custPermId;
    }

    /**
     * Sets the value of the custPermId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustPermId(String value) {
        this.custPermId = value;
    }

    /**
     * Gets the value of the examNameAliasInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMNameAliasInd() {
        return examNameAliasInd;
    }

    /**
     * Sets the value of the examNameAliasInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMNameAliasInd(String value) {
        this.examNameAliasInd = value;
    }

    /**
     * Gets the value of the examCustomerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMCustomerName() {
        return examCustomerName;
    }

    /**
     * Sets the value of the examCustomerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMCustomerName(String value) {
        this.examCustomerName = value;
    }

    /**
     * Gets the value of the legalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * Sets the value of the legalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalName(String value) {
        this.legalName = value;
    }

    /**
     * Gets the value of the examIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMIndicator() {
        return examIndicator;
    }

    /**
     * Sets the value of the examIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMIndicator(String value) {
        this.examIndicator = value;
    }

    /**
     * Gets the value of the examIdentSerialNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMIdentSerialNum() {
        return examIdentSerialNum;
    }

    /**
     * Sets the value of the examIdentSerialNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMIdentSerialNum(String value) {
        this.examIdentSerialNum = value;
    }

    /**
     * Gets the value of the examGovIssueIdentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMGovIssueIdentType() {
        return examGovIssueIdentType;
    }

    /**
     * Sets the value of the examGovIssueIdentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMGovIssueIdentType(String value) {
        this.examGovIssueIdentType = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the examCustCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMCustCategory() {
        return examCustCategory;
    }

    /**
     * Sets the value of the examCustCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMCustCategory(String value) {
        this.examCustCategory = value;
    }

    /**
     * Gets the value of the birthDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDt() {
        return birthDt;
    }

    /**
     * Sets the value of the birthDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDt(XMLGregorianCalendar value) {
        this.birthDt = value;
    }

    /**
     * Gets the value of the examCountryofCitizenship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMCountryofCitizenship() {
        return examCountryofCitizenship;
    }

    /**
     * Sets the value of the examCountryofCitizenship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMCountryofCitizenship(String value) {
        this.examCountryofCitizenship = value;
    }

    /**
     * Gets the value of the examCustSegmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMCustSegmentCode() {
        return examCustSegmentCode;
    }

    /**
     * Sets the value of the examCustSegmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMCustSegmentCode(String value) {
        this.examCustSegmentCode = value;
    }

    /**
     * Gets the value of the examInsiderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMInsiderCode() {
        return examInsiderCode;
    }

    /**
     * Sets the value of the examInsiderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMInsiderCode(String value) {
        this.examInsiderCode = value;
    }

    /**
     * Gets the value of the custType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustType() {
        return custType;
    }

    /**
     * Sets the value of the custType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustType(String value) {
        this.custType = value;
    }

    /**
     * Gets the value of the examCustCreatedDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEXAMCustCreatedDt() {
        return examCustCreatedDt;
    }

    /**
     * Sets the value of the examCustCreatedDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEXAMCustCreatedDt(XMLGregorianCalendar value) {
        this.examCustCreatedDt = value;
    }

    /**
     * Gets the value of the examOfficerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMOfficerCode() {
        return examOfficerCode;
    }

    /**
     * Sets the value of the examOfficerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMOfficerCode(String value) {
        this.examOfficerCode = value;
    }

    /**
     * Gets the value of the examShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMShortName() {
        return examShortName;
    }

    /**
     * Sets the value of the examShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMShortName(String value) {
        this.examShortName = value;
    }

    /**
     * Gets the value of the examPreAuthInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMPreAuthInd() {
        return examPreAuthInd;
    }

    /**
     * Sets the value of the examPreAuthInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMPreAuthInd(String value) {
        this.examPreAuthInd = value;
    }

    /**
     * Gets the value of the examEmployeeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMEmployeeCode() {
        return examEmployeeCode;
    }

    /**
     * Sets the value of the examEmployeeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMEmployeeCode(String value) {
        this.examEmployeeCode = value;
    }

    /**
     * Gets the value of the examProviderSystemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMProviderSystemCode() {
        return examProviderSystemCode;
    }

    /**
     * Sets the value of the examProviderSystemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMProviderSystemCode(String value) {
        this.examProviderSystemCode = value;
    }

    /**
     * Gets the value of the examSearchSelection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMSearchSelection() {
        return examSearchSelection;
    }

    /**
     * Sets the value of the examSearchSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMSearchSelection(String value) {
        this.examSearchSelection = value;
    }

    /**
     * Gets the value of the examSearchOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMSearchOption() {
        return examSearchOption;
    }

    /**
     * Sets the value of the examSearchOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMSearchOption(String value) {
        this.examSearchOption = value;
    }

    /**
     * Gets the value of the examFiller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMFiller() {
        return examFiller;
    }

    /**
     * Sets the value of the examFiller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMFiller(String value) {
        this.examFiller = value;
    }

    /**
     * Gets the value of the examOfficerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMOfficerName() {
        return examOfficerName;
    }

    /**
     * Sets the value of the examOfficerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMOfficerName(String value) {
        this.examOfficerName = value;
    }

    /**
     * Gets the value of the examAltId property.
     * 
     * @return
     *     possible object is
     *     {@link EXAMGovIssueIdentType }
     *     
     */
    public EXAMGovIssueIdentType getEXAMAltId() {
        return examAltId;
    }

    /**
     * Sets the value of the examAltId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXAMGovIssueIdentType }
     *     
     */
    public void setEXAMAltId(EXAMGovIssueIdentType value) {
        this.examAltId = value;
    }

    /**
     * Gets the value of the examCustSubCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMCustSubCategory() {
        return examCustSubCategory;
    }

    /**
     * Sets the value of the examCustSubCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMCustSubCategory(String value) {
        this.examCustSubCategory = value;
    }

    /**
     * Gets the value of the examStrategicBusinessUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMStrategicBusinessUnit() {
        return examStrategicBusinessUnit;
    }

    /**
     * Sets the value of the examStrategicBusinessUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMStrategicBusinessUnit(String value) {
        this.examStrategicBusinessUnit = value;
    }

    /**
     * Gets the value of the examSubSBUCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMSubSBUCode() {
        return examSubSBUCode;
    }

    /**
     * Sets the value of the examSubSBUCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMSubSBUCode(String value) {
        this.examSubSBUCode = value;
    }

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctId(String value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the acctType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctType() {
        return acctType;
    }

    /**
     * Sets the value of the acctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctType(String value) {
        this.acctType = value;
    }

    /**
     * Gets the value of the examCloseAcctFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMCloseAcctFlag() {
        return examCloseAcctFlag;
    }

    /**
     * Sets the value of the examCloseAcctFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMCloseAcctFlag(String value) {
        this.examCloseAcctFlag = value;
    }

    /**
     * Gets the value of the examConsolAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMConsolAcctId() {
        return examConsolAcctId;
    }

    /**
     * Sets the value of the examConsolAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMConsolAcctId(String value) {
        this.examConsolAcctId = value;
    }

    /**
     * Gets the value of the examRelationshipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXAMRelationshipCode() {
        return examRelationshipCode;
    }

    /**
     * Sets the value of the examRelationshipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXAMRelationshipCode(String value) {
        this.examRelationshipCode = value;
    }


}
