
package com.theerut.springj11.client.webservice.accountsummary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EXAM_AcctSummSvc", targetNamespace = "http://www.EXAMBusinessServices.org/EXAM_AcctSummSvc/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EXAMAcctSummSvc_1 {


    /**
     * 
     * @param accountSummary
     */
    @WebMethod(operationName = "EXAM_AcctSummSvc", action = "http://www.EXAMBusinessServices.org/EXAM_AcctSummSvc/EXAM_AcctSummSvc")
    void examAcctSummSvc(
            @WebParam(name = "EXAM_AcctSummSvc", targetNamespace = "http://webservice.ie.com", mode = WebParam.Mode.INOUT, partName = "AccountSummary")
                    Holder<EXAMAcctSummSvc> accountSummary);

}
