
package com.theerut.springj11.client.webservice.accountsummary;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "EXAM_AcctSummSvc", targetNamespace = "http://www.EXAMBusinessServices.org/EXAM_AcctSummSvc/", wsdlLocation = "file:/Users/krydtin/NetBeansProjects/EXAM/src/main/resources/Schema/wsdl/EXAM_AcctSummSvc%20v1.0.wsdl")
public class EXAMAcctSummSvc_Service
        extends Service {

    private final static URL EXAMACCTSUMMSVC_WSDL_LOCATION;
    private final static WebServiceException EXAMACCTSUMMSVC_EXCEPTION;
    private final static QName EXAMACCTSUMMSVC_QNAME = new QName("http://www.EXAMBusinessServices.org/EXAM_AcctSummSvc/", "EXAM_AcctSummSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/krydtin/NetBeansProjects/EXAM/src/main/resources/Schema/wsdl/EXAM_AcctSummSvc%20v1.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMACCTSUMMSVC_WSDL_LOCATION = url;
        EXAMACCTSUMMSVC_EXCEPTION = e;
    }

    public EXAMAcctSummSvc_Service() {
        super(__getWsdlLocation(), EXAMACCTSUMMSVC_QNAME);
    }

    public EXAMAcctSummSvc_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMACCTSUMMSVC_QNAME, features);
    }

    public EXAMAcctSummSvc_Service(URL wsdlLocation) {
        super(wsdlLocation, EXAMACCTSUMMSVC_QNAME);
    }

    public EXAMAcctSummSvc_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMACCTSUMMSVC_QNAME, features);
    }

    public EXAMAcctSummSvc_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EXAMAcctSummSvc_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns EXAMAcctSummSvc
     */
    @WebEndpoint(name = "EXAM_AcctSummSvcSOAP")
    public EXAMAcctSummSvc_1 getEXAMAcctSummSvcSOAP() {
        return super.getPort(new QName("http://www.EXAMBusinessServices.org/EXAM_AcctSummSvc/", "EXAM_AcctSummSvcSOAP"), EXAMAcctSummSvc_1.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns EXAMAcctSummSvc
     */
    @WebEndpoint(name = "EXAM_AcctSummSvcSOAP")
    public EXAMAcctSummSvc_1 getEXAMAcctSummSvcSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.EXAMBusinessServices.org/EXAM_AcctSummSvc/", "EXAM_AcctSummSvcSOAP"), EXAMAcctSummSvc_1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMACCTSUMMSVC_EXCEPTION != null) {
            throw EXAMACCTSUMMSVC_EXCEPTION;
        }
        return EXAMACCTSUMMSVC_WSDL_LOCATION;
    }

}
