
package com.theerut.springj11.client.webservice.accounttrxhistory;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EXAM_DepAcctTrnInqSvc", targetNamespace = "http://www.example.org/EXAM_DepAcctTrnInqSvc/", wsdlLocation = "file:/Users/examth/Documents/deposit/IDMs%20WDSLs%20%20XSDs/CASATransactionHistory/02%20Schema%20Definition/EXAM_DepAcctTrnInqSvc_v1.0.wsdl")
public class EXAMDepAcctTrnInqSvc_Service
    extends Service
{

    private final static URL EXAMDEPACCTTRNINQSVC_WSDL_LOCATION;
    private final static WebServiceException EXAMDEPACCTTRNINQSVC_EXCEPTION;
    private final static QName EXAMDEPACCTTRNINQSVC_QNAME = new QName("http://www.example.org/EXAM_DepAcctTrnInqSvc/", "EXAM_DepAcctTrnInqSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/examth/Documents/deposit/IDMs%20WDSLs%20%20XSDs/CASATransactionHistory/02%20Schema%20Definition/EXAM_DepAcctTrnInqSvc_v1.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMDEPACCTTRNINQSVC_WSDL_LOCATION = url;
        EXAMDEPACCTTRNINQSVC_EXCEPTION = e;
    }

    public EXAMDepAcctTrnInqSvc_Service() {
        super(__getWsdlLocation(), EXAMDEPACCTTRNINQSVC_QNAME);
    }

    public EXAMDepAcctTrnInqSvc_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMDEPACCTTRNINQSVC_QNAME, features);
    }

    public EXAMDepAcctTrnInqSvc_Service(URL wsdlLocation) {
        super(wsdlLocation, EXAMDEPACCTTRNINQSVC_QNAME);
    }

    public EXAMDepAcctTrnInqSvc_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMDEPACCTTRNINQSVC_QNAME, features);
    }

    public EXAMDepAcctTrnInqSvc_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EXAMDepAcctTrnInqSvc_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EXAMDepAcctTrnInqSvc
     */
    @WebEndpoint(name = "EXAM_DepAcctTrnInqSvcSOAP")
    public EXAMDepAcctTrnInqSvc getEXAMDepAcctTrnInqSvcSOAP() {
        return super.getPort(new QName("http://www.example.org/EXAM_DepAcctTrnInqSvc/", "EXAM_DepAcctTrnInqSvcSOAP"), EXAMDepAcctTrnInqSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EXAMDepAcctTrnInqSvc
     */
    @WebEndpoint(name = "EXAM_DepAcctTrnInqSvcSOAP")
    public EXAMDepAcctTrnInqSvc getEXAMDepAcctTrnInqSvcSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/EXAM_DepAcctTrnInqSvc/", "EXAM_DepAcctTrnInqSvcSOAP"), EXAMDepAcctTrnInqSvc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMDEPACCTTRNINQSVC_EXCEPTION!= null) {
            throw EXAMDEPACCTTRNINQSVC_EXCEPTION;
        }
        return EXAMDEPACCTTRNINQSVC_WSDL_LOCATION;
    }

}
