
package com.theerut.springj11.client.webservice.accounttrxhistory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EXAM_DepAcctTrnInqSvc", targetNamespace = "http://www.example.org/EXAM_DepAcctTrnInqSvc/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EXAMDepAcctTrnInqSvc_1 {


    /**
     * 
     * @param casaTransactionHistory
     */
    @WebMethod(operationName = "EXAM_DepAcctTrnInqSvc", action = "http://www.EXAMBusinessServices.org/EXAM_DepAcctTrnInqSvc/EXAM_DepAcctTrnInqSvc")
    void examDepAcctTrnInqSvc(
            @WebParam(name = "EXAM_DepAcctTrnInqSvc", targetNamespace = "urn:ifxforum-org:XSD:1", mode = WebParam.Mode.INOUT, partName = "CASATransactionHistory")
                    Holder<EXAMDepAcctTrnInqSvc> casaTransactionHistory);

}
